app:
  db_path: "./data/app.db"
  base_url: "http://127.0.0.1:9000"

fetch:
  source: "stub"
  per_creator_limit: 30
  polite_sleep_ms: [10000, 20000]
  only_update_recent_days_stats: 7

push:
  enabled: true
  provider: serverchan
  serverchan:
    sendkey: ""
  daily:
    group: "必看"
    hours: 24
    limit: 50
    sample: 5
    max_items: 5

bilibili:
  timeout_sec: 15
  cookie: "SESSDATA=7fa70c82%2C1785507116%2C113f9%2A22CjDXFnrJPrVq9mvsK4IchnrXNhBtonNiy5-VN0e0EOo-agOXDudIPIzyPvNjp-gS6fISVjVjeDd3MmRiTG5XYjdfdmRjZlBOeTQ0Vk1ScHBrRHh3YlZ1MVJiamRWaHVYbUZoX09Lb1ctNUtZd1U3cXRuSEZyTW1nMlZtdjBieVhrc25wZGJZNmNnIIEC; bili_jct=cb8315d4ae8e6c0d70a99653905a3ab0; DedeUserID=382373353"

rsshub:
  base_url: "http://127.0.0.1:1200"
  route_template: "/bilibili/user/video/{uid}"

creators:
  - uid: 123456
    name: "UP1"
    group: "必看"
    enabled: true
    priority: 1
    weight: 200
  - uid: 234567
    name: "UP2"
    group: "必看"
    enabled: true
    priority: 0
    weight: 100
